### ISSUE TITLE
Include 'api-key' in bcoin.example.conf

### ISSUE THREAD

**Issue by JoePotentier** [bcoin-org/bcoin-docker#10]
I was having issues connecting to my local bcoin instance. I wasn't using the Nginx-proxy so I thought my connections issues had something to do with that.

My app was connecting using the Node package and the only error I was getting was "socket hung up'. After swapping to the CLI I got 'Error: Unauthorized (bad API key)'. So finally I tried copying my API key over to the configuration file that I had created in the /secrets folder.

Once that was done the rpc/http port started accepting connections as normal.

I'd suggest adding 'api-key' to bcoin.example.conf to avoid this confusion in the future.

**Comment by JoePotentier** [comment]
And nevermind, the bcoin node package is still throwing the same error.

**Comment by pinheadmz** [comment]
Joe are you still getting an error with this? I'm a little unclear what your configuration is and what the problem is.

**Comment by JoePotentier** [comment]
@pinheadmz I had accidentally mounted a volume with existing bcoin configuration files. This meant that the wallet API was still using 127.0.0.1 which would not map outside of the container. This was my bad.
